### ISSUE TITLE
Create materials for Pandas intro

### ISSUE THREAD

**Issue by arokem** [uwescience/ds4ad#6]
- [ ] Reading data from CSV files
- [ ] Indexing
- [ ] Selecting rows, colums, combinations

Some material for this could be derived from: https://github.com/swcarpentry/python-novice-gapminder

**Comment by arokem** [comment]
Some materials from last time: https://github.com/arokem/2017-12-11-escience

But it's pretty choppy, to be honest. Best to rely on the SWC python gapminder materials.

**Comment by bhazelton** [comment]
Done. may still get a few edits, but we can go with what's there.
